apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-backend
  namespace: fleet-management
  annotations:
    iam.gke.io/gcp-service-account: fleet-backend@fleetos-492609.iam.gserviceaccount.com
