resources:
  - namespace.yaml
  - backend-serviceaccount.yaml
  - backend-configmap.yaml
  - backend-deployment.yaml
  - backend-hpa.yaml
  - backend-service.yaml
  - queue-deployment.yaml
  - reverb-deployment.yaml
  - reverb-service.yaml
  - telemetry-ingest-deployment.yaml
  - telemetry-ingest-service.yaml
  - telemetry-ingest-hpa.yaml
  - telemetry-queue-deployment.yaml
  - telemetry-queue-hpa.yaml
  - scheduler-cronjob.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - mailpit-deployment.yaml
  - mailpit-service.yaml
  - ingress.yaml
