apiVersion: apps/v1
kind: Deployment
metadata:
  name: mailpit
  namespace: fleet-management
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mailpit
  template:
    metadata:
      labels:
        app: mailpit
    spec:
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      containers:
        - name: mailpit
          image: axllent/mailpit:v1.29.0
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 1025
              name: smtp
            - containerPort: 8025
              name: http
          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop: ["ALL"]
            runAsNonRoot: true
            runAsUser: 1000
            runAsGroup: 1000
          resources:
            requests:
              cpu: 50m
              memory: 64Mi
            limits:
              cpu: 200m
              memory: 128Mi
