namespace: fleet-management

resources:
  - ../../base/namespace.yaml
  - ../../base/backend-serviceaccount.yaml
  - ../../base/backend-configmap.yaml

patches:
  - target:
      kind: ServiceAccount
      name: fleet-backend
    patch: |-
      - op: add
        path: /metadata/annotations
        value:
          iam.gke.io/gcp-service-account: fleet-backend@fleetos-492609.iam.gserviceaccount.com
  - target:
      kind: ConfigMap
      name: backend-config
    patch: |-
      - op: replace
        path: /data/APP_URL
        value: http://LOAD_BALANCER_IP
      - op: replace
        path: /data/FRONTEND_URL
        value: http://LOAD_BALANCER_IP
      - op: replace
        path: /data/SANCTUM_STATEFUL_DOMAINS
        value: LOAD_BALANCER_IP
      - op: replace
        path: /data/CORS_ALLOWED_ORIGINS
        value: http://LOAD_BALANCER_IP
